name: run

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        input: [templates]
        output: [dist]

    steps:
      - uses: alveshelio/mjml-to-html-github-action@latest
        with:
          input: ${{matrix.input}}
          output: ${{matrix.output}}
